close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/opt/genapp/rotdif/bin/main_rotdif.py", line 47, in <module>
    output_res, base_dir, dyna_flag, elm_flag, elmdock_flag = rotdif(to_dock)
ValueError: need more than 2 values to unpack
